// src/data/menu.ts

import type { Menu } from "./menu.interface";

export const menu: Menu = {
  restaurante: "Pizzería Don Tomate",
  telefono: "521XXXXXXXXXX",
  horario: "Lun–Dom 1:00 pm – 10:00 pm",

  masas: [
    {
      id: 1,
      tipo: "delgada",
      descripcion: "Crujiente y ligera",
      img: "/img/menu/masa-delgada.jpg",
    },
    {
      id: 2,
      tipo: "gruesa",
      descripcion: "Esponjosa y abundante",
      img: "/img/menu/masa-gruesa.jpg",
    },
    {
      id: 3,
      tipo: "rellena",
      descripcion: "Orilla rellena de queso",
      img: "/img/menu/masa-rellena.jpg",
    },
    {
      id: 4,
      tipo: "integral",
      descripcion: "Masa de trigo integral",
      img: "/img/menu/masa-integral.jpg",
    },
  ],

  pizzas: [
    {
      id: 1,
      imagen: "/img/menu/menu-1.jpg",
      nombre: "Margarita",
      descripcion: "La clásica italiana con sabor auténtico",
      categoria: "clasica",
      popular: false,
      masasDisponibles: ["delgada", "gruesa", "rellena", "integral"],
      ingredientes: [
        { nombre: "Salsa de tomate", esExtra: false },
        { nombre: "Queso mozzarella", esExtra: false },
        { nombre: "Albahaca fresca", esExtra: false },
      ],
      precios: [
        { tamano: "personal", valor: 89 },
        { tamano: "chica", valor: 119 },
        { tamano: "mediana", valor: 159 },
        { tamano: "grande", valor: 199 },
        { tamano: "extragrande", valor: 239 },
      ],
    },
    {
      id: 2,
      imagen: "/img/menu/menu-2.jpg",
      nombre: "Pepperoni",
      descripcion: "La favorita de siempre, cargada de pepperoni",
      categoria: "clasica",
      popular: true,
      masasDisponibles: ["delgada", "gruesa", "rellena", "integral"],
      ingredientes: [
        { nombre: "Salsa de tomate", esExtra: false },
        { nombre: "Queso mozzarella", esExtra: false },
        { nombre: "Pepperoni", esExtra: false },
      ],
      precios: [
        { tamano: "personal", valor: 99 },
        { tamano: "chica", valor: 129 },
        { tamano: "mediana", valor: 169 },
        { tamano: "grande", valor: 219 },
        { tamano: "extragrande", valor: 259 },
      ],
    },
    {
      id: 3,
      imagen: "/img/menu/menu-3.jpg",
      nombre: "Hawaiana",
      descripcion: "El clásico debate: jamón y piña en perfecta armonía",
      categoria: "clasica",
      popular: false,
      masasDisponibles: ["delgada", "gruesa", "rellena"],
      ingredientes: [
        { nombre: "Salsa de tomate", esExtra: false },
        { nombre: "Queso mozzarella", esExtra: false },
        { nombre: "Jamón", esExtra: false },
        { nombre: "Piña", esExtra: false },
      ],
      precios: [
        { tamano: "personal", valor: 99 },
        { tamano: "chica", valor: 129 },
        { tamano: "mediana", valor: 169 },
        { tamano: "grande", valor: 209 },
        { tamano: "extragrande", valor: 249 },
      ],
    },
    {
      id: 4,
      imagen: "/img/menu/menu-4.jpg",
      nombre: "Mexicana",
      descripcion: "Con todo el sabor picante de México",
      categoria: "especial",
      popular: true,
      masasDisponibles: ["delgada", "gruesa", "rellena"],
      ingredientes: [
        { nombre: "Salsa de tomate", esExtra: false },
        { nombre: "Queso mozzarella", esExtra: false },
        { nombre: "Chorizo", esExtra: false },
        { nombre: "Jalapeños", esExtra: false },
        { nombre: "Cebolla", esExtra: false },
        { nombre: "Chile morrón", esExtra: false },
      ],
      precios: [
        { tamano: "personal", valor: 109 },
        { tamano: "chica", valor: 149 },
        { tamano: "mediana", valor: 189 },
        { tamano: "grande", valor: 239 },
        { tamano: "extragrande", valor: 279 },
      ],
    },
    {
      id: 5,
      imagen: "/img/menu/menu-5.jpg",
      nombre: "Cuatro Quesos",
      descripcion:
        "Para los amantes del queso: mozzarella, gouda, manchego y parmesano",
      categoria: "especial",
      popular: true,
      masasDisponibles: ["delgada", "gruesa", "rellena", "integral"],
      ingredientes: [
        { nombre: "Salsa blanca", esExtra: false },
        { nombre: "Mozzarella", esExtra: false },
        { nombre: "Gouda", esExtra: false },
        { nombre: "Manchego", esExtra: false },
        { nombre: "Parmesano", esExtra: false },
      ],
      precios: [
        { tamano: "personal", valor: 119 },
        { tamano: "chica", valor: 159 },
        { tamano: "mediana", valor: 209 },
        { tamano: "grande", valor: 259 },
        { tamano: "extragrande", valor: 309 },
      ],
    },
    {
      id: 6,
      imagen: "/img/menu/menu-6.jpg",
      nombre: "BBQ Chicken",
      descripcion: "Pollo a la BBQ con cebolla morada caramelizada",
      categoria: "especial",
      popular: false,
      masasDisponibles: ["delgada", "gruesa", "rellena"],
      ingredientes: [
        { nombre: "Salsa BBQ", esExtra: false },
        { nombre: "Queso mozzarella", esExtra: false },
        { nombre: "Pollo a la parrilla", esExtra: false },
        { nombre: "Cebolla morada", esExtra: false },
        { nombre: "Cilantro", esExtra: false },
      ],
      precios: [
        { tamano: "personal", valor: 109 },
        { tamano: "chica", valor: 149 },
        { tamano: "mediana", valor: 199 },
        { tamano: "grande", valor: 249 },
        { tamano: "extragrande", valor: 289 },
      ],
    },
    {
      id: 7,
      imagen: "/img/menu/menu-7.jpg",
      nombre: "Vegetariana",
      descripcion: "Fresca y colorida, cargada de verduras de temporada",
      categoria: "vegetariana",
      popular: false,
      masasDisponibles: ["delgada", "gruesa", "integral"],
      ingredientes: [
        { nombre: "Salsa de tomate", esExtra: false },
        { nombre: "Queso mozzarella", esExtra: false },
        { nombre: "Champiñones", esExtra: false },
        { nombre: "Pimiento rojo", esExtra: false },
        { nombre: "Espinaca", esExtra: false },
        { nombre: "Cebolla", esExtra: false },
        { nombre: "Aceitunas", esExtra: false },
      ],
      precios: [
        { tamano: "personal", valor: 99 },
        { tamano: "chica", valor: 139 },
        { tamano: "mediana", valor: 179 },
        { tamano: "grande", valor: 219 },
        { tamano: "extragrande", valor: 259 },
      ],
    },
    {
      id: 8,
      imagen: "/img/menu/menu-8.jpg",
      nombre: "Especial de la Casa",
      descripcion: "Todo lo que nos gusta junto en una sola pizza",
      categoria: "especial",
      popular: true,
      masasDisponibles: ["delgada", "gruesa", "rellena"],
      ingredientes: [
        { nombre: "Salsa de tomate", esExtra: false },
        { nombre: "Queso mozzarella", esExtra: false },
        { nombre: "Pepperoni", esExtra: false },
        { nombre: "Jamón", esExtra: false },
        { nombre: "Chorizo", esExtra: false },
        { nombre: "Champiñones", esExtra: false },
        { nombre: "Pimiento", esExtra: false },
        { nombre: "Cebolla", esExtra: false },
      ],
      precios: [
        { tamano: "personal", valor: 129 },
        { tamano: "chica", valor: 169 },
        { tamano: "mediana", valor: 219 },
        { tamano: "grande", valor: 269 },
        { tamano: "extragrande", valor: 319 },
      ],
    },
  ],

  combos: [
    {
      id: 1,
      nombre: "Combo Familiar",
      descripcion: "Ideal para compartir en familia",
      incluye: [
        "1 pizza grande a elegir",
        "1 pizza mediana a elegir",
        "4 refrescos 355ml",
        "1 orden de pan de ajo",
      ],
      precio: 429,
      popular: true,
    },
    {
      id: 2,
      nombre: "Combo Pareja",
      descripcion: "Para una noche perfecta de dos",
      incluye: ["2 pizzas medianas a elegir", "2 refrescos 355ml"],
      precio: 299,
      popular: false,
    },
    {
      id: 3,
      nombre: "Combo Personal",
      descripcion: "Justo para ti",
      incluye: [
        "1 pizza personal a elegir",
        "1 refresco 355ml",
        "1 orden de alitas (6 pzas)",
      ],
      precio: 179,
      popular: false,
    },
    {
      id: 4,
      nombre: "Combo Fiesta",
      descripcion: "Para la reunión del finde",
      incluye: [
        "3 pizzas grandes a elegir",
        "6 refrescos 355ml",
        "2 órdenes de pan de ajo",
        "1 postre a elegir",
      ],
      precio: 749,
      popular: false,
    },
  ],

  extras: [
    { id: 1, nombre: "Ingrediente extra", precio: 20 },
    { id: 2, nombre: "Orilla rellena", precio: 35 },
    { id: 3, nombre: "Pan de ajo (4 pzas)", precio: 55 },
    { id: 4, nombre: "Alitas BBQ (6 pzas)", precio: 89 },
    { id: 5, nombre: "Alitas picosas (6 pzas)", precio: 89 },
    { id: 6, nombre: "Palitos de queso", precio: 65 },
    { id: 7, nombre: "Aderezo extra", precio: 15 },
  ],

  bebidas: [
    {
      id: 1,
      nombre: "Refresco",
      opciones: [
        { descripcion: "355ml lata", precio: 25 },
        { descripcion: "600ml", precio: 35 },
        { descripcion: "1.5L", precio: 55 },
        { descripcion: "2L", precio: 65 },
      ],
    },
    {
      id: 2,
      nombre: "Agua mineral",
      opciones: [
        { descripcion: "500ml", precio: 20 },
        { descripcion: "1L", precio: 35 },
      ],
    },
    {
      id: 3,
      nombre: "Agua de horchata",
      opciones: [
        { descripcion: "500ml", precio: 25 },
        { descripcion: "1L", precio: 40 },
      ],
    },
  ],

  postres: [
    {
      id: 1,
      nombre: "Brownie de chocolate",
      descripcion: "Tibio con helado de vainilla",
      precio: 65,
    },
    {
      id: 2,
      nombre: "Cannoli",
      descripcion: "Relleno de crema de ricotta",
      precio: 55,
    },
    {
      id: 3,
      nombre: "Gelato",
      descripcion: "Sabores: vainilla, fresa, pistache",
      precio: 45,
    },
  ],
};
